# Generated by Django 3.2.5 on 2021-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fs', 'Farsi')], default='en', help_text='Written language', max_length=2),
        ),
    ]
