# Generated by Django 3.1.2 on 2021-07-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
