# Generated by Django 3.1.2 on 2021-07-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210713_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_identify_borrower', 'Privileged view of borrower identity')]},
        ),
    ]
