# Generated by Django 3.1.2 on 2021-07-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210714_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_identify_borrower', 'View borrower identity')]},
        ),
    ]
