# Generated by Django 3.2.5 on 2021-07-30 18:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fornavn', models.CharField(help_text='Personens officielle fornavn(e) som i protokol', max_length=50)),
                ('efternavn', models.CharField(help_text='Personens officielle efternavn(e) som i protokol', max_length=50)),
                ('kaldenavn', models.CharField(help_text='Det navn, personen ønsker brugt i daglig tiltale', max_length=15)),
                ('unilogin', models.CharField(help_text='Personens officielle fornavn(e) som i protokol', max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('mail', models.EmailField(help_text='Mail, læreren kan bruge til kommunikation med eleven', max_length=254)),
                ('mobil', models.CharField(help_text='Mobiltelefonnummer, system og lærer kan bruge til kommunikation med eleven', max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('note', models.TextField(help_text='Lærerens noter om eleven, elevens lokale eller historik. OBS der er mulighed andetsteds for løbende observationsnoter.', max_length=200)),
            ],
            options={
                'verbose_name': 'elev',
                'verbose_name_plural': 'elever',
                'ordering': ['klasse', 'fornavn', 'efternavn'],
            },
        ),
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Emne-løbenummer (automatisk)')),
                ('titel', models.CharField(help_text='Betegnelse for emnet', max_length=20)),
                ('fag', models.CharField(choices=[('mat', 'Matematik'), ('it', 'Informationsteknologi')], default='Matematik', max_length=3)),
                ('studieretning', models.CharField(choices=[('stx', 'STX'), ('hf', 'HF'), ('htx', 'HTX'), ('hhx', 'HHX'), ('eux', 'EUX'), ('eud', 'EUD'), ('etc', 'Andet')], default='stx', help_text='Klassens studieretning', max_length=3)),
                ('faglige_mål', models.TextField(help_text='Bekendtgørelsens og skolens faggruppes krav til emnet', max_length=1000)),
                ('note', models.TextField(help_text='Lærerens krav til og ambitioner for emnet', max_length=1000)),
                ('klassetrin', models.IntegerField(help_text='Årgang, emnet undervises på (siden holdets startår)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('varighed', models.IntegerField(help_text='Forventet antal lektioner/moduler')),
            ],
            options={
                'verbose_name_plural': 'emner',
                'ordering': ['fag', 'studieretning', 'klassetrin', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Forløb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Forløbs-løbenummer (automatisk)')),
                ('titel', models.CharField(help_text='Overskrift for forløbet', max_length=20)),
                ('påbegyndt', models.DateField(help_text='Dato for planlagt start af forløbet')),
                ('varighed', models.IntegerField(help_text='Forventet antal lektioner/moduler')),
                ('kommentar', models.TextField(help_text='Præsentation til holdets elever af det konkrete forløb i klassen', max_length=500)),
                ('emne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.emne')),
            ],
            options={
                'ordering': ['klasse', 'emne'],
            },
        ),
        migrations.CreateModel(
            name='Skole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text='Skolens officielle navn', max_length=100)),
                ('kortnavn', models.CharField(help_text='Skolens korte navn', max_length=20)),
            ],
            options={
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Løbenummer (automatisk) for videopræsentation')),
                ('stillet', models.DateField(help_text='Dato, hvor opgaven blev stillet til elev (eller hold)')),
                ('frist', models.DateTimeField(help_text='Dato og tid for seneste aftalte aflevering')),
                ('indleveret', models.DateField(help_text='Dato og tid for faktisk aflevering')),
                ('opgave', models.CharField(help_text='Opgavetekst for SOLO aktivitet', max_length=100)),
                ('url', models.URLField(help_text='Videoens placering (fx skjult på YouTube)')),
                ('egen_solo', models.CharField(choices=[('pre', 'Præstrukturelt niveau'), ('uni', 'Unistrukturelt niveau'), ('mul', 'Multistrukturelt niveau'), ('rel', 'Relationelt niveau'), ('udv', 'Udvidet-abstrakt niveau')], max_length=3, null=True, verbose_name='Elevens egen bedømmelse efter SOLO')),
                ('lærer_solo', models.CharField(choices=[('pre', 'Præstrukturelt niveau'), ('uni', 'Unistrukturelt niveau'), ('mul', 'Multistrukturelt niveau'), ('rel', 'Relationelt niveau'), ('udv', 'Udvidet-abstrakt niveau')], max_length=3, null=True)),
                ('egen_bedømmelse', models.CharField(max_length=100, null=True, verbose_name='Elevens egen bedømmelse i fri tekst')),
                ('lærer_bedømmelse', models.CharField(max_length=100, null=True)),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prepare.elev')),
                ('forløb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prepare.forløb')),
            ],
            options={
                'ordering': ['forløb', 'frist', 'elev'],
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Modul-løbenummer (automatisk)')),
                ('afholdt', models.DateField(help_text='Dato for planlagt start af forløbet')),
                ('forløb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.forløb')),
            ],
            options={
                'verbose_name_plural': 'moduler',
                'ordering': ['afholdt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text='Holdets administrative navn', max_length=100)),
                ('kortnavn', models.CharField(help_text='Holdets  korte navn', max_length=20)),
                ('startår', models.IntegerField(help_text='Firecifret årstal for holdstart', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)])),
                ('fokus_runde', models.IntegerField(help_text='(automatisk) løbenummer for samplingsrunde til fokusgruppe', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('fokus_antal', models.IntegerField(help_text='Standardstørrelse af klassens fokusgruppe', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('note', models.TextField(help_text='Lærerens generelle noter om holdet, dets lokale eller historik', max_length=200)),
                ('skole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.skole')),
            ],
            options={
                'verbose_name': 'klasse',
                'verbose_name_plural': 'klasser',
                'ordering': ['navn'],
            },
        ),
        migrations.AddField(
            model_name='forløb',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.klasse'),
        ),
        migrations.CreateModel(
            name='FokusGruppe',
            fields=[
                ('elev_fg_runde_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fokusgruppens Elev-løbenummer')),
                ('bedømt', models.BooleanField(null=True)),
                ('rand_rank', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('elev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.elev')),
                ('modul', models.ManyToManyField(null=True, to='prepare.Modul')),
            ],
            options={
                'verbose_name': 'fokusgruppe til adfærdsobservation',
                'verbose_name_plural': 'fokusgrupper til adfærdsobservation',
                'ordering': ['elev_fg_runde_id', 'elev'],
            },
        ),
        migrations.AddField(
            model_name='elev',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='prepare.klasse'),
        ),
        migrations.CreateModel(
            name='Adfærd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Løbenummer (automatisk) for adfærdsobservation')),
                ('tilstede', models.BooleanField(default=True)),
                ('spørg', models.IntegerField(help_text='Score for elevens evne til at søge hjælp på fagligt spørgsmål', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('hjælp', models.IntegerField(help_text='Score for elevens evne til at yde hjælp til faglig problemløsning', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('faglig', models.IntegerField(help_text='Score for elevens evne til at bidrage til en faglig samtale', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('stikord', models.CharField(help_text='Lærerens observationer i ord', max_length=30)),
                ('reaktion', models.CharField(help_text='Elevens bemærkning', max_length=30)),
                ('fokusgruppe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prepare.fokusgruppe')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prepare.modul')),
            ],
            options={
                'verbose_name': 'adfærdsobservation',
                'verbose_name_plural': 'adfærdsobservationer',
            },
        ),
    ]
