# Generated by Django 3.2.5 on 2021-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fokusgruppe',
            name='modul',
            field=models.ManyToManyField(to='prepare.Modul'),
        ),
    ]
