# Generated by Django 3.2.5 on 2021-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0002_alter_skole_oprettet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfærd',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adfærd',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='elev',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='elev',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emne',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emne',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forløb',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forløb',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='klasse',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='klasse',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modul',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modul',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='opdateret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='oprettet',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
