# Generated by Django 3.2.5 on 2021-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0003_auto_20210730_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='kaldenavn',
            field=models.CharField(help_text='Det navn, personen ønsker brugt i daglig tiltale', max_length=15, null=True),
        ),
    ]
