# Generated by Django 3.2.5 on 2021-08-01 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0004_auto_20210801_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='studieretning',
            field=models.CharField(choices=[('stx', 'STX'), ('hf', 'HF'), ('htx', 'HTX'), ('hhx', 'HHX'), ('eux', 'EUX'), ('eud', 'EUD'), ('etc', 'Andet')], default='stx', help_text='Klassens studieretning', max_length=3),
        ),
        migrations.AlterField(
            model_name='klasse',
            name='fokus_antal',
            field=models.IntegerField(default=5, help_text='Standardstørrelse af klassens fokusgruppe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='klasse',
            name='fokus_runde',
            field=models.IntegerField(help_text='(automatisk) løbenummer for samplingsrunde til fokusgruppe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
