# Generated by Django 3.2.5 on 2021-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0005_auto_20210730_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='note',
            field=models.TextField(blank=True, help_text='Lærerens noter om eleven, elevens lokale eller historik. OBS der er mulighed andetsteds for løbende observationsnoter.', max_length=200, null=True),
        ),
    ]
