# Generated by Django 3.2.5 on 2021-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0007_auto_20210808_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fokusgruppe',
            name='faglig',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at bidrage til en faglig samtale', null=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='hjælp',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at yde hjælp til faglig problemløsning', null=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='reaktion',
            field=models.CharField(blank=True, help_text='Elevens bemærkning', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='spørg',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at søge hjælp på fagligt spørgsmål', null=True),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='stikord',
            field=models.CharField(blank=True, help_text='Lærerens observationer i "tre" ord', max_length=30, null=True),
        ),
    ]
