# Generated by Django 3.2.5 on 2021-08-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0008_auto_20210808_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fokusgruppe',
            name='modul',
        ),
        migrations.AddField(
            model_name='fokusgruppe',
            name='modul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prepare.modul'),
        ),
    ]
