# Generated by Django 3.2.5 on 2021-07-31 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0008_auto_20210731_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skole',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 13, 39, 27, 130125)),
        ),
        migrations.AlterField(
            model_name='skole',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 13, 39, 27, 130082)),
        ),
    ]
