# Generated by Django 3.2.5 on 2021-07-31 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0009_auto_20210731_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasse',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 13, 52, 28, 969034)),
        ),
        migrations.AddField(
            model_name='klasse',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 13, 52, 28, 968993)),
        ),
        migrations.AlterField(
            model_name='skole',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skole',
            name='oprettet',
            field=models.DateTimeField(),
        ),
    ]
