# Generated by Django 3.2.5 on 2021-08-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0009_auto_20210808_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elev',
            options={'ordering': ['klasse', 'fornavn', 'efternavn'], 'verbose_name_plural': 'elever'},
        ),
    ]
