# Generated by Django 3.2.5 on 2021-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0010_auto_20210731_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasse',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='klasse',
            name='oprettet',
            field=models.DateTimeField(),
        ),
    ]
