# Generated by Django 3.2.5 on 2021-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0011_elev_indmeldt'),
    ]

    operations = [
        migrations.AddField(
            model_name='elev',
            name='udmeldt',
            field=models.DateField(blank=True, help_text='Dato for hvornår eleven er holdt op med at gå i klassen', null=True),
        ),
    ]
