# Generated by Django 3.2.5 on 2021-07-31 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0012_alter_skole_opdateret'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfærd',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 723375)),
        ),
        migrations.AddField(
            model_name='adfærd',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 723334)),
        ),
        migrations.AddField(
            model_name='elev',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 716868)),
        ),
        migrations.AddField(
            model_name='elev',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 716827)),
        ),
        migrations.AddField(
            model_name='emne',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 720153)),
        ),
        migrations.AddField(
            model_name='emne',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 720115)),
        ),
        migrations.AddField(
            model_name='fokusgruppe',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 718107)),
        ),
        migrations.AddField(
            model_name='fokusgruppe',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 718069)),
        ),
        migrations.AddField(
            model_name='forløb',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 721358)),
        ),
        migrations.AddField(
            model_name='forløb',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 721316)),
        ),
        migrations.AddField(
            model_name='modul',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 722431)),
        ),
        migrations.AddField(
            model_name='modul',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 722389)),
        ),
        migrations.AddField(
            model_name='video',
            name='opdateret',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 724588)),
        ),
        migrations.AddField(
            model_name='video',
            name='oprettet',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 18, 52, 724547)),
        ),
    ]
