# Generated by Django 3.2.5 on 2021-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0012_elev_udmeldt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adfærd',
        ),
        migrations.AddConstraint(
            model_name='fokusgruppe',
            constraint=models.UniqueConstraint(fields=('elev', 'modul'), name='unik_modul_elev'),
        ),
    ]
