# Generated by Django 3.2.5 on 2021-08-28 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0013_auto_20210823_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fokusgruppe',
            name='faglig',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at bidrage til en faglig samtale', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='hjælp',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at yde hjælp til faglig problemløsning', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='spørg',
            field=models.IntegerField(blank=True, help_text='Score for elevens evne til at søge hjælp på fagligt spørgsmål', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
