# Generated by Django 3.2.5 on 2021-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepare', '0014_auto_20210731_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfærd',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adfærd',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='elev',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='elev',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emne',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emne',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fokusgruppe',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forløb',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='forløb',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modul',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modul',
            name='oprettet',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='opdateret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='oprettet',
            field=models.DateTimeField(),
        ),
    ]
